address: "4/F, Immigration Tower, 7 Gloucester Road, Wan Chai, Hong Kong"
latitude: 22.396428
longitude: 114.109497
name: "Immigration - Travel Documents and Nationality (Application) Section & Travel Documents (Issue) Section"
